version: '3'

services:
  redis:
      image: redis:latest

  db:
    image: postgres:latest
    env_file:
      - ./.env
    # ports:
    #   - "5432:5432"
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  
  web:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py createsu &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
